const fields = [
  {
    categoryName: "driving",
    generalFields: [
      "date",
      "time",
      "location",
      "wind direction",
      "course/range",
      "tournament week",
      "completion time",
      "number of balls",
      "why",
      "goals",
    ],
    mainDrillTypes: [
      "fairway specific driving",
      "driver escalator",
      "10 of the best",
    ],
    inputFields: [
      "club",
      "shape/flight",
      "lie before",
      "carry",
      "driving distance",
      "lie after",
      "club speed",
      "ball speed",
      "target l-r",
      "% dispersion driver",
      "sg driver",
    ],
    drillCompletionData: ["notes", "what are you working on"],
    additionalDrillTypes: [],
  },
  {
    categoryName: "approach",
    generalFields: [
      "date",
      "time",
      "location",
      "wind direction",
      "course/range",
      "tournament week",
      "completion time",
      "number of balls",
      "why",
      "goals",
    ],
    mainDrillTypes: [
      {
        mainDrillTypeName: "skills development full & back foot flighted",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s--l",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        mainDrillTypeName: "shot shaping approach play",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s--l",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        mainDrillTypeName: "par 5 approach play",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s--l",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        mainDrillTypeName: "pin practice range",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        mainDrillTypeName: "fairway bunker iron session",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        mainDrillTypeName: "stance session",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
    ],
    drillCompletionData: ["notes", "what are you working on"],
    additionalDrillTypes: [
      {
        additionalDrillTypeName: "flight scope iron session 75-125",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "flight scope iron session 100-150",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "flight scope iron session 125-175",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "flight scope iron session 150-200",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "flight scope iron session 175-225",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "flight scope iron session 50-150",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "flight scope iron session 100-200",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "club speed",
          "ball speed",
          "true target l-r",
          "true target s-l",
          "lie after",
          "target proximity l-r",
          "target proximity s-l",
          "pin proximity l-r",
          "pin proximity s-l",
          "pin proximity",
          "proximity",
          "short side",
          "% dispersion approach",
          "sg approach",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants test 100-125",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants test 125-150",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants test 150-175",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants test 175-200",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants sloping lies 115-130",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants sloping lies 140-160",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants sloping lies 170-190",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
      {
        additionalDrillTypeName: "grove quadrants sloping lies 190-200",
        beforePracticeShot: [
          "club",
          "distance",
          "pin position",
          "lie before",
          "shape/flight",
        ],
        afterPracticeShot: [
          "true target l-r",
          "true target s-l",
          "lie after",
          "short side",
          "shots before",
          "shots after",
        ],
      },
    ],
  },
  {
    categoryName: "pitching",
    generalFields: [
      "date",
      "time",
      "location",
      "weather",
      "wind direction",
      "grass type",
      "course/range",
      "tournament week",
      "completion time",
      "number of balls",
      "why",
      "goals",
    ],
    mainDrillTypes: [
      "skills development full & back foot flighted",
      "shot shaping approach play",
      "par 5 approach play",
      "pin practice range",
      "fairway bunker iron session",
      "stance session",
    ],
    beforePracticeShot: [
      "club",
      "distance",
      "pin position",
      "lie before",
      "swing position",
      "shape/flight",
    ],
    afterPracticeShot: [
      "club speed",
      "ball speed",
      "lie after",
      "target s-l",
      "target l-r",
      "pin proximity",
      "short side",
      "proximity",
      "% dispersion approach",
      "sg pitching",
      "pitching shots before",
      "pitching shots after",
    ],
    drillCompletionData: ["notes", "what are you working on"],
    additionalDrillTypes: [
      "flight scope iron session 75-125",
      "flight scope iron session 100-150",
      "flight scope iron session 125-175",
      "flight scope iron session 150-200",
      "flight scope iron session 175-225",
      "flight scope iron session 50-150",
      "flight scope iron session 100-200",
      "grove quadrants test 100-125",
      "grove quadrants test 125-150",
      "grove quadrants test 150-175",
      "grove quadrants test 175-200",
      "grove quadrants sloping lies 115-130",
      "grove quadrants sloping lies 140-160",
      "grove quadrants sloping lies 170-190",
      "grove quadrants sloping lies 190-200",
    ],
  },
];
